### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by saraiva1989** [GeadSolutions/lvdesk#1]
Oi, meu nome é Daniel e sou desenvolvedor no Brasil.
Consegui o acesso ao seu banco de dados. 

Quero ajudar de forma gratuita, caso veja esse mensagem, entre em contato para eu explicar como corrigir essa falha.

![image](https://user-images.githubusercontent.com/40599423/105651830-ab7af700-5e96-11eb-9244-18d4d9561916.png)

**Comment by GeadSolutions** [comment]
Bom dia! Como vai vc Daniel?
Apesar deste projeto ter sido interrompido, ficaria muito feliz em saber o
que melhorar nesse script.
Cordialmente,
Adan Ribeiro

Em Dom, 24 de jan de 2021 22:51, Daniel Saraiva <notifications@github.com>
escreveu:

**Comment by saraiva1989** [comment]
Eu não sei se **desenvolvimento de software** é sua area de atuação, mas as informações de conexão com o banco de dados está no github e publico para qualquer pessoa ver.
Caso uma pessoa má intencionada queira, pode deletar seu banco, criptografar ou pegar os dados de acesso e vender.

Outra coisa muito ruim é que a senha está com criptografia MD5, que é possível decriptar facilmente. Assim eu consigo ver o login e senha do usuário.

Mesmo que o sistema não seja mais utilizado, sabemos que 90% das pessoas usam o mesmo login e senha para tudo. Sabendo o login que usa em seu sistema e decriptando a senha posso conseguir acessar o email de alguma dessas pessoas.

E pior com a **LGPD** se esses dados forem publicados pode gerar multa para o responsável pelos dados.

Minhas recomendações são:

1. Se o projeto está inativo e não irá voltar Delete o banco de dados e o código do github.
2. Se quer manter o código aberto no github, delete o repositório e crie um novo sem as informações da conexão com o banco de dados.
3. Se Não quer alterar nada no github, pode ver na sua hospedagem para bloquear o acesso do banco de dados. Assim permitindo acesso apenas a IP especificos.


Espero ter ajudado e caso tenha qualquer duvida pode me chamar.

caso queira fazer uma doação fica o link do paypal
https://www.paypal.com/donate?hosted_button_id=EN9JK4LL787AA

**Caso não possa fazer a doação, ajude um pessoa com um abraço :-)**
